services:
  - type: web
    name: finances
    runtime: ruby
    plan: free
    buildCommand: '.render-build.sh'
    startCommand: 'bundle exec rails server'
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2