default: &default
  adapter: oracle_enhanced
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: sitesefin
  password: site2880
  database: //exa01-scan.sefin.ro.gov.br:1521/producao

test:
  <<: *default
  username:
  password:
  database: //exa01-scan.sefin.ro.gov.br:1521/desenv

production:
  <<: *default
  username: sitesefin
  password: site2880
  database: //exa01-scan.sefin.ro.gov.br:1521/producao