development:
  adapter: sqlite3
  timeout: 5000
  database: storage/development.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.production.database.host %>
  database: <%= Rails.application.credentials.production.database.database %>
  username: <%= Rails.application.credentials.production.database.username %>
  password: <%= Rails.application.credentials.production.database.password %>
