source "https://rubygems.org"

ruby "3.0.1"

gem "rails", "7.1.5.1"
gem "puma", "6.6.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", "1.18.6", require: false

group :development do
    gem "sqlite3", "2.0.4"
end

group :production do
    gem "pg", "1.5.9"
end