source "https://rubygems.org"

ruby "3.0.1"

gem "rails", "7.1.5.1"
gem "sqlite3", "2.0.4"
gem "puma", "6.6.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", "1.18.6", require: false